### PR TITLE
Add a baseline (expected output) for test.py

### PR DESCRIPTION
**Pull request by foolip**
Force test.py to output UTF-8 to make this work.

### CODE REVIEW

**Comment by foolip** [comment]
@plinss I'd like to set up CI testing for this as well. Would you prefer using Travis, GitHub Actions, or something else? Although it's in beta, I can recommend GitHub Actions. You can sign up at https://github.com/features/actions if you'd like to.

**Comment by foolip** [comment]
https://github.com/tabatkins/bikeshed/pull/1514#issuecomment-526531799 is what prompted me to do this. Applying these changes to commits 9faf8f81b4d93332d6c1b2a4bcea6aaabb038e62 and c1f30088df0d1cf460acdcbe01ff5e4bbcb2640c, the difference in output between those two are:
```diff
--- test-expected.txt	2019-08-30 12:14:22.136833838 +0200
+++ test-actual.txt	2019-08-30 12:14:39.384955905 +0200
@@ -76,7 +76,9 @@
     void anotherMethod(short round);
     [ha!] attribute short bar getraises (an, exception);
     const short fortyTwo = 42;
-    long foo(long x, long y);
+    attribute long async;
+    long foo(long x, long y, long async);
+    long includes();
 }
 [ NoInterfaceObject , MapClass (short, Foo )] interface LinkStyle {
     stringifier attribute DOMString mediaText;
@@ -211,32 +213,32 @@
 
 IGNORED LEGACY IDL LINE: 76 - "getraises (an, exception)"
 
-IDL SYNTAX ERROR LINE: 80 - expected ";" 
+IDL SYNTAX ERROR LINE: 82 - expected ";" 
 
-IDL SYNTAX ERROR LINE: 89 - skipped: "this is a syntax error, naturally
+IDL SYNTAX ERROR LINE: 91 - skipped: "this is a syntax error, naturally
 "
 
-IDL SYNTAX ERROR LINE: 97 - expected ";" 
+IDL SYNTAX ERROR LINE: 99 - expected ";" 
 
-IGNORED LEGACY IDL LINE: 100 - "setraises (for the heck of it)"
+IGNORED LEGACY IDL LINE: 102 - "setraises (for the heck of it)"
 
-IDL SYNTAX ERROR LINE: 123 - skipped: "attribute long error"
+IDL SYNTAX ERROR LINE: 125 - skipped: "attribute long error"
 
-IDL ERROR LINE: 138 - Dictionary argument "optionalDict" without required members must be marked optional
+IDL ERROR LINE: 140 - Dictionary argument "optionalDict" without required members must be marked optional
 
-IDL ERROR LINE: 139 - Dictionary argument "optionalDict" without required members must be marked optional
+IDL ERROR LINE: 141 - Dictionary argument "optionalDict" without required members must be marked optional
 
-IDL SYNTAX ERROR LINE: 158 - skipped: "[NoInterfaceObject] Interface includes Mixin"
+IDL SYNTAX ERROR LINE: 160 - skipped: "[NoInterfaceObject] Interface includes Mixin"
 
-IDL SYNTAX ERROR LINE: 161 - skipped: "getter long (unsigned long argument)"
+IDL SYNTAX ERROR LINE: 163 - skipped: "getter long (unsigned long argument)"
 
-IDL SYNTAX ERROR LINE: 165 - skipped: "static readonly attribute long staticReadOnlyAttributeMember"
+IDL SYNTAX ERROR LINE: 167 - skipped: "static readonly attribute long staticReadOnlyAttributeMember"
 
-IDL SYNTAX ERROR LINE: 169 - skipped: "iterable<long>"
+IDL SYNTAX ERROR LINE: 171 - skipped: "iterable<long>"
 
-IDL SYNTAX ERROR LINE: 173 - skipped: "readonly maplike<DOMString, DOMString>"
+IDL SYNTAX ERROR LINE: 175 - skipped: "readonly maplike<DOMString, DOMString>"
 
-IDL SYNTAX ERROR LINE: 177 - skipped: "readonly setlike<DOMString>"
+IDL SYNTAX ERROR LINE: 179 - skipped: "readonly setlike<DOMString>"
 
 [Parser: [dictionary: [name: CSSFontFaceLoadEventInit] [inherits: EventInit][members: 
   [dict-member: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: [sequence] [TypeWithExtendedAttributes: [SingleType: [NonAnyType: u'CSSFontFaceRule']]]]]] [name: fontfaces] = [default: [Default: [ ]]]]
@@ -244,7 +246,7 @@
 [interface: [name: Simple] [members: 
   [unknown:  tokens: [identifier:serializer][symbol:;]]
   [unknown:  tokens: [identifier:serializer][whitespace: ][symbol:=][whitespace: ][symbol:{][whitespace: ][identifier:foo][whitespace: ][symbol:}][symbol:;]]
-  [member: [Operation: [Type: [SingleType: [NonAnyType: u'serializer']]] [OperationRest: [name: cereal] [argumentlist: [argument: [type: short ] [name: one]]]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: u'serializer']]] [OperationRest: [name: [OperationName: u'cereal']] [argumentlist: [argument: [type: short ] [name: one]]]]]]
   [member: [Iterable: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: u'Foo']]]]]
   [member: [Iterable: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: u'Foo']]] [TypeWithExtendedAttributes: [SingleType: [NonAnyType: u'Bar']]]]]
   [member: [AsyncIterable: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: u'Foo']]] [TypeWithExtendedAttributes: [SingleType: [NonAnyType: u'Bar']]]]]
@@ -252,8 +254,8 @@
   [member: [Setlike: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: Uint8ClampedArray]]]]]
   [member: [attribute: [AttributeRest: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: [PrimitiveType: u'boolean']]]] [name: required]]]]
   [member: [StaticMember: [AttributeRest: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: u'Foo']]] [name: foo]]]]
-  [member: [StaticMember: [Type: [SingleType: [NonAnyType: u'Foo']]] [OperationRest: [name: foo] [argumentlist: ]]]]
-  [member: [Operation: [Type: [SingleType: [NonAnyType: [Promise] [Type: [SingleType: [NonAnyType: u'ReallyISwear']]][null]]]] [OperationRest: [name: theCheckIsInTheMail] [argumentlist: ]]]]
+  [member: [StaticMember: [Type: [SingleType: [NonAnyType: u'Foo']]] [OperationRest: [name: [OperationName: u'foo']] [argumentlist: ]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: [Promise] [Type: [SingleType: [NonAnyType: u'ReallyISwear']]][null]]]] [OperationRest: [name: [OperationName: u'theCheckIsInTheMail']] [argumentlist: ]]]]
 ]]
 [interface: [name: Multi] [inherits: One][members: 
   [member: [attribute: [AttributeRest: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: short]]]]]] [name: one]]]]
@@ -268,7 +270,7 @@
 [unknown:  tokens: [symbol:typedef][whitespace: ][symbol:record][symbol:<][symbol:any][symbol:,][whitespace: ][symbol:any][symbol:>][whitespace: ][identifier:recordBroken][symbol:;]]
 [interface: [name: foo] [members: 
   [member: [Extended Attributes: [ExtendedAttributeNoArgs: one]] [attribute: [AttributeRest: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: u'Foo']]] [name: one]]]]
-  [member: [Extended Attributes: [ExtendedAttributeNoArgs: two]] [Operation: [Type: [SingleType: [NonAnyType: u'Foo']]] [OperationRest: [name: two] [argumentlist: ]]]]
+  [member: [Extended Attributes: [ExtendedAttributeNoArgs: two]] [Operation: [Type: [SingleType: [NonAnyType: u'Foo']]] [OperationRest: [name: [OperationName: u'two']] [argumentlist: ]]]]
   [member: [Extended Attributes: [ExtendedAttributeNoArgs: three]] [const: [ConstType: u'Foo'][name: three] = [value: 3]]]
 ]]
 [unknown:  tokens: [symbol:}]]
@@ -309,20 +311,22 @@
   [ExtendedAttributeIdent: NamedConstructor [value: MyConstructor]]
   [ExtendedAttributeArgList: Constructor [arguments: [argument: [type: Foo ] [name: one]]]]
   [ExtendedAttributeNamedArgList: NamedConstructor [value: MyOtherConstructor] [arguments: [argument: [type: Foo ] [name: two]] [argument: [type: long long ] [name: longest]]]]
-  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [unsigned][IntegerType: long long]]]]]] [OperationRest: [name: method] [argumentlist: [argument: [type: short ] [name: x]] [argument: [type: unsigned long long ] [name: y]] [argument: [optional] [type: double ] [name: inf] [default: [Default: [ConstValue: [FloatLiteral: Infinity]]]]] [argument: [type: sequence<Foo>][...] [name: fooArg]]]]]]
-  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [unsigned][IntegerType: long long]]]]]] [OperationRest: [name: method] [argumentlist: [argument: [type: DOMString ] [name: string]] [argument: [optional] [type: Foo ] [name: foo] [default: [Default: {}]]]]]]]
-  [member: [Operation: void [OperationRest: [name: abort] [argumentlist: ]]]]
-  [member: [Operation: void [OperationRest: [name: anotherMethod] [argumentlist: [argument: [type: short ] [name: round]]]]]]
-  [member: [Extended Attributes: [ExtendedAttribute: [identifier:ha][other:!]]] [attribute: [AttributeRest: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: short]]]]]] [name: bar]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [unsigned][IntegerType: long long]]]]]] [OperationRest: [name: [OperationName: u'method']] [argumentlist: [argument: [type: short ] [name: x]] [argument: [type: unsigned long long ] [name: y]] [argument: [optional] [type: double ] [name: inf] [default: [Default: [ConstValue: [FloatLiteral: Infinity]]]]] [argument: [type: sequence<Foo>][...] [name: fooArg]]]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [unsigned][IntegerType: long long]]]]]] [OperationRest: [name: [OperationName: u'method']] [argumentlist: [argument: [type: DOMString ] [name: string]] [argument: [optional] [type: Foo ] [name: foo] [default: [Default: {}]]]]]]]
+  [member: [Operation: void [OperationRest: [name: [OperationName: u'abort']] [argumentlist: ]]]]
+  [member: [Operation: void [OperationRest: [name: [OperationName: u'anotherMethod']] [argumentlist: [argument: [type: short ] [name: round]]]]]]
+  [member: [Extended Attributes: [ExtendedAttribute: [identifier:ha][other:!]]] [attribute: [AttributeRest: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: short]]]]]] [name: bar ]]]]
   [member: [const: [ConstType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: short]]]][name: fortyTwo] = [value: 42]]]
-  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [OperationRest: [name: foo] [argumentlist: [argument: [type: long ] [name: x]] [argument: [type: long ] [name: y]]]]]]
+  [member: [attribute: [AttributeRest: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [name: async]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [OperationRest: [name: [OperationName: u'foo']] [argumentlist: [argument: [type: long ] [name: x]] [argument: [type: long ] [name: y]] [argument: [type: long ] [name: async]]]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [OperationRest: [name: [OperationName: u'includes']] [argumentlist: ]]]]
 ]]
 [interface: [Extended Attributes: [ExtendedAttributeNoArgs: NoInterfaceObject] [ExtendedAttributeTypePair: MapClass [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: short]]]]]] [Type: [SingleType: [NonAnyType: u'Foo']]]]] [name: LinkStyle] [members: 
   [member: [Stringifier: [AttributeRest: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: DOMString]]] [name: mediaText]]]]
   [member: [attribute: [AttributeRest: [readonly] [TypeWithExtendedAttributes: [Extended Attributes: [ExtendedAttributeNoArgs: Extended]] [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: short]]]]]] [name: bar]]]]
   [member: [SpecialOperation: [getter] [Type: [SingleType: [NonAnyType: object]]] [OperationRest: [argumentlist: [argument: [type: DOMString ] [name: name]]]]]]
-  [member: [SpecialOperation: [getter] [setter] [Type: [SingleType: [NonAnyType: object]]] [OperationRest: [name: bob] [argumentlist: [argument: [type: DOMString ] [name: name]]]]]]
-  [member: [Stringifier: [Type: [SingleType: [NonAnyType: u'foo']]] [OperationRest: [name: me] [argumentlist: [argument: [type: int ] [name: x]]]]]]
+  [member: [SpecialOperation: [getter] [setter] [Type: [SingleType: [NonAnyType: object]]] [OperationRest: [name: [OperationName: u'bob']] [argumentlist: [argument: [type: DOMString ] [name: name]]]]]]
+  [member: [Stringifier: [Type: [SingleType: [NonAnyType: u'foo']]] [OperationRest: [name: [OperationName: u'me']] [argumentlist: [argument: [type: int ] [name: x]]]]]]
   [member: [Stringifier: [Type: [SingleType: [NonAnyType: u'foo']]] [OperationRest: [argumentlist: ]]]]
   [member: [Stringifier: ]]
   [member: [Stringifier: [AttributeRest: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: short]]]]]] [name: string]]]]
@@ -337,10 +341,10 @@
 [callback: [name: callFoo] [returnType: short] [argumentlist: ]]
 [callback: [name: callFoo2] [returnType: unsigned long long] [argumentlist: [argument: [type: unrestricted double ] [name: one]] [argument: [type: DOMString ] [name: two]] [argument: [type: Fubar ][...] [name: three]]]]
 [callback: [interface: [name: callMe] [members: 
-  [member: [attribute: [inherit] [AttributeRest: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: short]]]]]] [name: round]]]]
+  [member: [attribute: [inherit] [AttributeRest: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: short]]]]]] [name: round ]]]]
 ]]]
 [callback: [interface: [mixin] [name: callMeMixin] [members: 
-  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [OperationRest: [name: method] [argumentlist: ]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [OperationRest: [name: [OperationName: u'method']] [argumentlist: ]]]]
 ]]]
 [dictionary: [Extended Attributes: [ExtendedAttributeIdentList: Exposed [value: Window] Worker]] [name: MyDictionary] [members: 
   [dict-member: [TypeWithExtendedAttributes: [SingleType: any]] [name: value] = [default: [Default: [ConstValue: u'null']]]]
@@ -354,26 +358,26 @@
   [member: [attribute: [AttributeRest: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: ArrayBuffer[null]]]] [name: value3]]]]
 ]]
 [namespace: [name: Namespace1] [members: 
-  [member: [Extended Attributes: [ExtendedAttributeNoArgs: One]] [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [unsigned][IntegerType: long long]]]]]] [OperationRest: [name: method] [argumentlist: [argument: [Extended Attributes: [ExtendedAttributeNoArgs: Extended]] [type: short ] [name: x]]]]]]
-  [member: [Extended Attributes: [ExtendedAttributeNoArgs: Two]] [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [unsigned][IntegerType: long long]]]]]] [OperationRest: [name: method] [argumentlist: [argument: [type: short ] [name: x]] [argument: [type: short ] [name: y]]]]]]
+  [member: [Extended Attributes: [ExtendedAttributeNoArgs: One]] [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [unsigned][IntegerType: long long]]]]]] [OperationRest: [name: [OperationName: u'method']] [argumentlist: [argument: [Extended Attributes: [ExtendedAttributeNoArgs: Extended]] [type: short ] [name: x]]]]]]
+  [member: [Extended Attributes: [ExtendedAttributeNoArgs: Two]] [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [unsigned][IntegerType: long long]]]]]] [OperationRest: [name: [OperationName: u'method']] [argumentlist: [argument: [type: short ] [name: x]] [argument: [type: short ] [name: y]]]]]]
   [member: [attribute: [AttributeRest: [readonly] [TypeWithExtendedAttributes: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]][TypeSuffix: [null] ]]]] [name: value]]]]
   [unknown:  tokens: [symbol:attribute][whitespace: ][symbol:long][whitespace: ][identifier:error][symbol:;]]
 ]]
 [namespace: [partial] [name: Namespace2] [members: 
-  [member: [Extended Attributes: [ExtendedAttributeNoArgs: One]] [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [unsigned][IntegerType: long long]]]]]] [OperationRest: [name: method] [argumentlist: [argument: [type: short ] [name: x]]]]]]
-  [member: [Extended Attributes: [ExtendedAttributeNoArgs: Two]] [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [unsigned][IntegerType: long long]]]]]] [OperationRest: [name: method] [argumentlist: [argument: [type: short ] [name: x]] [argument: [type: short ] [name: y]]]]]]
+  [member: [Extended Attributes: [ExtendedAttributeNoArgs: One]] [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [unsigned][IntegerType: long long]]]]]] [OperationRest: [name: [OperationName: u'method']] [argumentlist: [argument: [type: short ] [name: x]]]]]]
+  [member: [Extended Attributes: [ExtendedAttributeNoArgs: Two]] [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [unsigned][IntegerType: long long]]]]]] [OperationRest: [name: [OperationName: u'method']] [argumentlist: [argument: [type: short ] [name: x]] [argument: [type: short ] [name: y]]]]]]
 ]]
 [interface: [name: System] [members: 
-  [member: [Operation: [Type: [SingleType: [NonAnyType: object]]] [OperationRest: [name: createObject] [argumentlist: [argument: [type: DOMString ] [name: interface]]]]]]
-  [member: [Operation: [Type: [SingleType: [NonAnyType: [sequence] [TypeWithExtendedAttributes: [SingleType: [NonAnyType: object]]]]]] [OperationRest: [name: getObjects] [argumentlist: [argument: [type: DOMString ] [name: interface]]]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: object]]] [OperationRest: [name: [OperationName: u'createObject']] [argumentlist: [argument: [type: DOMString ] [name: interface]]]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: [sequence] [TypeWithExtendedAttributes: [SingleType: [NonAnyType: object]]]]]] [OperationRest: [name: [OperationName: u'getObjects']] [argumentlist: [argument: [type: DOMString ] [name: interface]]]]]]
   [member: [SpecialOperation: [getter] [Type: [SingleType: [NonAnyType: DOMString]]] [OperationRest: [argumentlist: [argument: [type: DOMString ] [name: keyName]]]]]]
-  [member: [Operation: [Type: [SingleType: [NonAnyType: DOMString[TypeSuffix: [null] ]]]] [OperationRest: [name: lookupPrefix] [argumentlist: [argument: [type: DOMString? ] [name: namespace]]]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: DOMString[TypeSuffix: [null] ]]]] [OperationRest: [name: [OperationName: u'lookupPrefix']] [argumentlist: [argument: [type: DOMString? ] [name: namespace]]]]]]
 ]]
 [interface: [name: OptionalTest] [members: 
-  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [OperationRest: [name: methodWithOptionalDict] [argumentlist: [argument: [type: long ] [name: one]] [argument: [type: (long or MyDictionary or object) ] [name: optionalDict]]]]]]
-  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [OperationRest: [name: methodWithOptionalDict] [argumentlist: [argument: [type: long ] [name: one]] [argument: [type: MyDictionary ] [name: optionalDict]] [argument: [optional] [type: long ] [name: three]]]]]]
-  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [OperationRest: [name: methodWithRequiredDict] [argumentlist: [argument: [type: long ] [name: one]] [argument: [type: FooDict ] [name: requiredDict]]]]]]
-  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [OperationRest: [name: methodWithRequiredDict] [argumentlist: [argument: [type: long ] [name: one]] [argument: [type: FooDict ] [name: requiredDict]] [argument: [type: long ] [name: three]]]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [OperationRest: [name: [OperationName: u'methodWithOptionalDict']] [argumentlist: [argument: [type: long ] [name: one]] [argument: [type: (long or MyDictionary or object) ] [name: optionalDict]]]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [OperationRest: [name: [OperationName: u'methodWithOptionalDict']] [argumentlist: [argument: [type: long ] [name: one]] [argument: [type: MyDictionary ] [name: optionalDict]] [argument: [optional] [type: long ] [name: three]]]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [OperationRest: [name: [OperationName: u'methodWithRequiredDict']] [argumentlist: [argument: [type: long ] [name: one]] [argument: [type: FooDict ] [name: requiredDict]]]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [OperationRest: [name: [OperationName: u'methodWithRequiredDict']] [argumentlist: [argument: [type: long ] [name: one]] [argument: [type: FooDict ] [name: requiredDict]] [argument: [type: long ] [name: three]]]]]]
 ]]
 [interface: [name: Interface] [members: 
   [member: [attribute: [AttributeRest: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [name: hello]]]]
@@ -382,7 +386,7 @@
   [member: [const: [ConstType: [PrimitiveType: [UnrestrictedFloatType: [FloatType: double]]]][name: constantMember] = [value: 10.0]]]
   [member: [attribute: [AttributeRest: [readonly] [TypeWithExtendedAttributes: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [name: readOnlyAttributeMember]]]]
   [member: [attribute: [AttributeRest: [TypeWithExtendedAttributes: [SingleType: [NonAnyType: [PrimitiveType: [UnsignedIntegerType: [IntegerType: long]]]]]] [name: attributeMember]]]]
-  [member: [Operation: [Type: [SingleType: [NonAnyType: DOMString[TypeSuffix: [null] ]]]] [OperationRest: [name: operationMember] [argumentlist: [argument: [type: long ] [name: argument]]]]]]
+  [member: [Operation: [Type: [SingleType: [NonAnyType: DOMString[TypeSuffix: [null] ]]]] [OperationRest: [name: [OperationName: u'operationMember']] [argumentlist: [argument: [type: long ] [name: argument]]]]]]
   [member: [Stringifier: ]]
 ]]
 [includes: [name: Interface] [includes: Mixin]]
@@ -481,7 +485,9 @@
     <c method><k>void</k> <n>anotherMethod</n>(<c argument><t><p><k>short</k></p></t> <n>round</n></c>);</c>
     <c attribute>[<c extended-attribute>ha!</c>] <k>attribute</k> <t><p><k>short</k></p></t> <n>bar</n> getraises (an, exception);</c>
     <c const><k>const</k> <t><p><k>short</k></p></t> <n>fortyTwo</n> = 42;</c>
-    <c method><t><p><k>long</k></p></t> <n>foo</n>(<c argument><t><p><k>long</k></p></t> <n>x</n></c>, <c argument><t><p><k>long</k></p></t> <n>y</n></c>);</c>
+    <c attribute><k>attribute</k> <t><p><k>long</k></p></t> <n>async</n>;</c>
+    <c method><t><p><k>long</k></p></t> <n>foo</n>(<c argument><t><p><k>long</k></p></t> <n>x</n></c>, <c argument><t><p><k>long</k></p></t> <n>y</n></c>, <c argument><t><p><k>long</k></p></t> <n>async</n></c>);</c>
+    <c method><t><p><k>long</k></p></t> <n>includes</n>();</c>
 }
 </c><c interface>[ <c extended-attribute><n>NoInterfaceObject</n></c> , <c extended-attribute><n>MapClass</n> (<p><k>short</k></p>, <tn>Foo</tn> )</c>] <k>interface</k> <n>LinkStyle</n> {
     <c attribute><k>stringifier</k> <k>attribute</k> <t><s><k>DOMString</k></s></t> <n>mediaText</n>;</c>
@@ -584,7 +590,7 @@
 };</c>
 
 
-Complexity: 134
+Complexity: 136
 dictionary: CSSFontFaceLoadEventInit
     dict-member: fontfaces (fontfaces)
 interface: Simple
@@ -655,9 +661,11 @@
     method: method(string, foo) (method)
     method: abort() (abort)
     method: anotherMethod(round) (anotherMethod)
-    attribute: bar (bar)
+    attribute: bar  (bar )
     const: fortyTwo (fortyTwo)
-    method: foo(x, y) (foo)
+    attribute: async (async)
+    method: foo(x, y, async) (foo)
+    method: includes() (includes)
 interface: LinkStyle
     attribute: mediaText (mediaText)
     attribute: bar (bar)
@@ -675,7 +683,7 @@
 callback: callFoo
 callback: callFoo2
 callback: callMe
-    attribute: round (round)
+    attribute: round  (round )
 callback: callMeMixin
     method: method() (method)
 dictionary: MyDictionary
@@ -726,7 +734,7 @@
 interface: MixinCanNotIncludeSetlike
     unknown: None (None)
 FIND:
-callMe/round
+Foo/anotherMethod(round)/round
 Foo/method(x, y, inf, ...fooArg)/y
 Foo/method(string, foo)
 Foo
```

Extra whitespace has crept in a few places, and I expect that's problem.

**Comment by plinss** [comment]
Thanks for this. I really need to improve the testing to a proper unit test (planned when I do the Python3 migration), but this helps in the meanwhile.

GitHub actions would be preferred for CI, signed up.

**Comment by foolip** [comment]
Great, I'll send a separate a PR to set that up next week.

**Pull request merged**
