### PR TITLE
Run test.py on GitHub Actions

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
https://github.com/foolip/widlparser/runs/208234296 shows that this ran successfully.

@plinss one could certainly make the output nicer and all, but I think this'll prevent accidents at least.

**Comment by foolip** [comment]
https://github.com/foolip/widlparser/pull/1 shows how this will look like when it fails, wanted to prove it works, now let's see if it does in this repo :)

**Comment by foolip** [comment]
Hmm, I don't see anything run on https://github.com/plinss/widlparser/commits/master yet, which suggests GitHub actions isn't enabled yet. @plinss can you check it?

**Comment by plinss** [comment]
I signed up for the beta, don't see any other places to turn it on, am I missing something?

AFAICT this will only run on pushes and pull requests, and there haven't been any since this was merged... feel free to make a test PR

**Comment by foolip** [comment]
Did you have the option of enabling it for any user/org?

When I signed up it was a request to join and not granted immediately, did you get any email saying you're enrolled?

**Comment by plinss** [comment]
I did get the option of which org to enable it for, but haven't gotten any email yet. Maybe Github just didn't turn it on yet...

**Comment by plinss** [comment]
Apparently I'm on the waitlist

**Comment by foolip** [comment]
Oh, I shouldn't have recommend GitHub Actions yet...

I can send the equivalent Travis setup if you want to use that in the interim, or if you wait you'll probably get it enabled soonish.

**Comment by plinss** [comment]
Let's just wait for a bit, this isn't all that critical as I can check the tests locally when making changes. GitHub Actions seems a lot like GitLab's CI which I'm already familiar with.

**Comment by foolip** [comment]
Yeah, free CI systems all seem to be getting better and converging in terms of capabilities recently. Azure Pipelines is great too :)

**Pull request merged**
